### ISSUE TITLE
script loaded via http

### ISSUE THREAD

**Issue by pachacamac** [gottfrois/link_thumbnailer_demo#1]
Mixed Content: The page at 'https://link-thumbnailer-demo.herokuapp.com/' was loaded over HTTPS, but requested an insecure script 'http://link-thumbnailer-api.herokuapp.com/thumbnails/new ...

therefore it doesn't work .. sorry no time for a pull request but thought I should at least leave an issue. Cool project btw :)

**Comment by gottfrois** [comment]
Hm i updated the cedar stack this weekend, might be the issue. Though I quickly checked and didn't run into that issue :(

Have you tried without https?

**Comment by pachacamac** [comment]
Yes, if I disable https-everywhere and force the site to load over http then it works. Either the script link is hardcoded to http (try using omitting the protocol in the link like `//:link-thumbnailer-api.herokuapp.com...`)  or your Rails app doesn't recognize the protocol automatically for some reason.

**Comment by gottfrois** [comment]
Yeah, probably the first case

**Comment by gottfrois** [comment]
this is deprecated now
